server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: uploadFiles/
      max-file-size: 20MB
      max-request-size: 50MB
      resolve-lazily: false
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL57Dialect

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://106.15.204.9:3306/paper_web?characterEncoding=utf8mb4&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ocr
    password: Ocr@123456